# Generated by Django 5.0.3 on 2024-07-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wedding',
            new_name='studentsmodel',
        ),
    ]
