# Generated by Django 5.0.3 on 2024-07-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0002_rename_wedding_studentsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmodel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
