  # Generated by Django 5.0.3 on 2024-07-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0003_alter_studentsmodel_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.IntegerField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=18)),
            ],
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
